import Head from "next/head";
import Banner from "../../components/homepage/banner";
import Services from "../../components/homepage/services";
import Stats from "../../components/homepage/Stats";
import Deals from "../../components/homepage/Deals";
import Regulate from "../../components/homepage/Regulate";
import Contact from "../../components/homepage/Contact";
import Review from "../../components/homepage/Review";
import { PostData, axiosGet } from "../../utils/ApiCalls";

export default function Home({ data, data2 }) {
  console.log("countdown data", data2);
  console.log("deal data", data);
  return (
    <>
      <Head>
        <title>Energise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner data={data} />
      <Services />
      <Stats />
      <Deals data2={data2} />
      <Regulate />
      <Contact />
      <Review />
    </>
  );
}

export async function getServerSideProps() {
  try {
    const data = await PostData("top-energy-deals");
    const data2 = await axiosGet('get-deals-data')
    console.log("countdown data", data2);
    console.log("deal data", data);
    return {
      props: { data: data, data2: data2 },
    };
  } catch (error) {
    console.error("Error fetching data:", error);
    return {
      props: { data: {}, data2: {} },
    };
  }
}
